### PR TITLE
Integrated composer and phpunit

### PR DESCRIPTION
**Pull request by eimanavicius**
Started to change plugin structure. Integrated composer and phpunit. Added travis-ci build config. Changed code style to PSR-2 where possible.
As bonus found and fixed bug with plugin load order function.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please consider following https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

**Comment by eimanavicius** [comment]
I choose PSR-2 because I see that plugin is done using OOP and I think that this coding style is better for this programming style.
I done some research about WP adopting PSR standarts and I found that it will never happen (https://core.trac.wordpress.org/ticket/23357, https://core.trac.wordpress.org/ticket/21300).
This plugin had no visible coding style. So choosing one or the other coding will not introduce bigger changes.
I choose to stay with PSR-2, unless its the only thing stopping this pull request.

**Comment by pelmered** [comment]
Hm, I've been a bit sloppy with the coding standards so far. 

I think we should use the WordPress coding standard because this is a WordPress plugin. However I don't think that is a problem for this pull request. I can fix this with PHP CodeSniffer/CodeFixer later.

I will review the changes more carefully and merge this within a few days.

**Comment by eimanavicius** [comment]
After changing coding style back and forth we make harder to trace code changes.
This pull request is huge and packed with several big moves.
Maybe we should split it apart? Do code formatting and cleaning from commented code, then testing tools, then introduce composer, then add travis-ci build config, then fix load_this_plugin_first function. What you think?

**Pull request merged**
